### PR TITLE
fix(sw): init assetCache correctly

### PR DESCRIPTION
**Pull request by denistex**
Hi guys,

First of all, thank you for the great project!

I noticed that asset cache is left undefined if I pass a `RemixCache` instance to the `PrecacheHandler` ctor.

Turns out, the `assetCache` local variable was left uninitialized if `this.assetCacheName` is not a string. The PR fixes this problem by handling `assetCache` the same way as it is done for `dataCache` and `documentCache`.

Let me know if I overlooked something. Thank you.

### CODE REVIEW

**Comment by ShafSpecs** [comment]
Merged :+1:. Would probably make the `commitlint` workflow an optional one since commit messages shouldn't break a whole run. You can view your changes by running `npm i @remix-pwa/sw@dev` or use the version number directly: `npm i @remix-pwa/sw@2.1.13-dev.1`

**Comment by ShafSpecs** [comment]
Thanks for the contribution btw 😊

**Comment by denistex** [comment]
Thanks again for the great project :+1: , I'm happy to help

**Comment by Sarabadu** [comment]
> Merged :+1:. Would probably make the `commitlint` workflow an optional one since commit messages shouldn't break a whole run. You can view your changes by running `npm i @remix-pwa/sw@dev` or use the version number directly: `npm i @remix-pwa/sw@2.1.13-dev.1`

Have in mind that commit messages determine when to release and which version assign with semantic release

**Pull request merged**
