### PR TITLE
Remix PWA + Vite pre-release

### PR DESCRIPTION
**Pull request by ShafSpecs**
Do I need to say anything else? 😆

### CODE REVIEW

**Comment by IgnisDa** [comment]
Just want to thank you for the great work! Can I help in testing? I have a pretty big remix app which uses vite.

**Comment by ShafSpecs** [comment]
> Just want to thank you for the great work! Can I help in testing? I have a pretty big remix app which uses vite.

Sure thing. There would be no docs this year tho, but would be writing an un-official docs in the meantime under this PR and in Discord. Thanks

**Comment by ShafSpecs** [comment]
The prerelease is out, you can tests it out by running `npm i @remix-pwa/dev@2.1.0-dev.1` or `npm i @remix-pwa@dev` and in your vite config file, import `unstable_RemixPWA` plugin

**Comment by ShafSpecs** [comment]
The plugin takes a few options, when I last tested it, it didn't have typing support enabled, to do so, add:
```js
import { unstable_RemixPWA as remixPwa } from "@remix-pwa/dev";
import type { PWAViteOptions } from "@remix-pwa/dev";

export default defineConfig({
  plugins: [
    // ...other plugins
    remixPwa(<Partial<PWAViteOptions>>{ // enables correct typing support...
      // remix-pwa plugin options
    }),
  ],
});
```

**Comment by ShafSpecs** [comment]
Typings are in! `npm i @remix-pwa/dev@dev` to get started

**Comment by fredericrous** [comment]
I'm getting the following issue

```
Directory import '/mvp/node_modules/.pnpm/@remix-pwa+cache@2.0.12/node_modules/buffer/' is not supported resolving ES modules imported from /mvp/node_modules/.pnpm/@remix-pwa+cache@2.0.12/node_modules/@remix-pwa/cache/dist/src/cache.js
Did you mean to import buffer@6.0.3/node_modules/buffer/index.js?
```

when I remove `useSWEffect();` from `root.tsx`, I do not get this error.

Another concern: `workerLoader` is triggered but `workerAction` does not seem to be triggered. would adding useSWEffect solve the issue when useSWEffect doesn't throw anymore?

**Comment by ShafSpecs** [comment]
> I'm getting the following issue on 2.1.0-dev.2
> 
> ```
> Directory import '/mvp/node_modules/.pnpm/@remix-pwa+cache@2.0.12/node_modules/buffer/' is not supported resolving ES modules imported from /mvp/node_modules/.pnpm/@remix-pwa+cache@2.0.12/node_modules/@remix-pwa/cache/dist/src/cache.js
> Did you mean to import buffer@6.0.3/node_modules/buffer/index.js?
> ```
> 
> when I remove `useSWEffect();` from `root.tsx`, I do not get this error.
> 
> Another concern: `workerLoader` is triggered but `workerAction` does not seem to be triggered. I'm using axios to post to https://webworker.local/ and the request fails without workerAction being triggered Would adding useSWEffect solve the issue when useSWEffect doesn't throw anymore?

The error thrown by `useSWEffect` is due to Vite's incompatibility with `@remix-pwa/cache`. I am yet to start working on that (this is a pre-release). About `workerAction` not getting triggered, would look at that tomorrow. That should be supported out of the box. Btw, one of the main reasons this is a prerelease is because other releases are going to be shipped with it 😄. When all that is fleshed out, the experience would be smooth.

Thanks for the bug reporting btw, helps me to quickly fix issues that tests can't catch

**Comment by ShafSpecs** [comment]
@fredericrous Dug a bit further and yeah, `workerAction` and `workerLoader` don't work because Remix doesn't support them
https://remix.run/docs/en/main/future/vite#strict-route-exports

**Comment by fredericrous** [comment]
if I put a debugger in workerLoader, it triggers tho. But indeed maybe it's unstable and might not work on every route.. looks like we are in a deadlock, at least for now. thank you for the quick feedbacks

**Comment by ShafSpecs** [comment]
> if I put a debugger in workerLoader, it triggers tho. But indeed maybe it's unstable and might not work on every route.. looks like we are in a deadlock, at least for now. thank you for the quick feedbacks

Hmm, weird it works. Which remix version are you using? I am utilizing 2.4.1 and it breaks totally, currently pushing for Remix to natively support worker route apis out of the box tho. But yeah, it is very unstable and the case is in a deadlock. Would hopefully get some progress before next year

**Comment by ShafSpecs** [comment]
@fredericrous Regarding `workerLoader`/`Action` not being supported, I've fixed that and a new pre-release would be out soon. Regarding `workerAction` not firing, found the culprit:
https://github.com/remix-pwa/monorepo/blob/d5aa5b4f99e3d6a4b1cab513a86339de3185de21/packages/worker-runtime/src/utils/handle-request.ts#L81-L89
Not yet found a solution tho, but working on it. Hopefully, would be out with those two fixes today

**Comment by ShafSpecs** [comment]
https://github.com/remix-pwa/monorepo/pull/129

Fixed the errors thrown by worker loaders, there's still one more issue tho with how remix handles fetching in Remix Vite. And that's why they triggered randomly. Hope to figure that out this week and bring route workers back online

**Comment by fredericrous** [comment]
@ShafSpecs now remix has [clientLoader](https://remix.run/docs/en/main/route/client-loader) which at least for my use case removes the need for workerLoader

**Comment by ShafSpecs** [comment]
> @ShafSpecs now remix has [clientLoader](https://remix.run/docs/en/main/route/client-loader) which at least for my use case removes the need for workerLoader

Thought so too. Till I realized they aren't the same. Client loader run in the browser, worker loader in the browser parallel to the client. Client loader won't work for offline scenarios so I still have to maintain them. But I've solved the main issues with them and they work now with vite.

The current delay is Remix still figuring out the Vite API in Remix in dev. Namely how assets are handled, previously, it was easy to just get the asset array and cache, but now you have to build and serve it to actually get assets working. Which means precaching becomes impossible in dev, and that's the theme of next update so I can't release without that API getting stabilized 😅

**Comment by ShafSpecs** [comment]
But yeah, you can use client loader in some situations where you needed worker loaders. But worker loaders are still super client loaders, cause they still intercept requests from client loaders

**Comment by typytypytypy** [comment]
can you clarify the current state of this? I tried using 
`yarn add @remix-pwa/dev@dev`

But then I get this error:
`error: Could not resolve "@remix-pwa/worker-runtime"`

**Comment by ShafSpecs** [comment]
> can you clarify the current state of this? I tried using `yarn add @remix-pwa/dev@dev`
> 
> But then I get this error: `error: Could not resolve "@remix-pwa/worker-runtime"`

This works fine

```yml
# Current versions to use/test the latest features
- @remix-pwa/sw: 2.2.0-dev.2  # dependency
- @remix-pwa/dev: 2.1.0-dev.5  # devDependency
- @remix-pwa/worker-runtime: 2.1.0-dev.1  # devDependency
```

**Pull request merged**
